name: Post Checkin Tasks

on:
  push:
    paths:
      - Preamble_Global.ultra
      - Preamble_QLever.ultra
      - Preamble_US.ultra
      - Query_Global.ultra
      - Query_QLever.ultra
      - Query_US.ultra
      - Style.ultra
  schedule:
    - cron: '0 0 * * 0' # Triggers every Sunday at midnight (UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-styles-and-newmascots:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      working-directory: ./newmascots
      run: dotnet restore

    - name: Build the project
      working-directory: ./newmascots
      run: dotnet build --no-restore --configuration Release

    - name: Run the program
      working-directory: ./newmascots
      run: dotnet run --no-build --configuration Release

    - name: Verify file generation
      run: |
        if [ ! -f NewMascots.txt ]; then
          echo "NewMascots.txt was not generated."
          exit 1
        fi

    - name: Concat style files
      run: |
        cat Preamble_US.ultra Style.ultra Query_US.ultra > HSMascotMap.ultra
        cat Preamble_Global.ultra Style.ultra Query_Global.ultra > HSMascotMap_global.ultra
        cat Preamble_QLever.ultra Style.ultra Query_QLever.ultra > HSMascotMap_QLever.ultra
        cat Preamble_Global.ultra Style.ultra Query_University_Global.ultra > HSMascotMap_university_global.ultra

    - name: Commit and push changes
      run: |        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A && git commit -m "Update files" || echo "No changes to commit"
        git push || echo "No changes to push"